name: cheapBuy
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - python -m pip install --upgrade pip
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
install:
  - pip install -r requirements.txt
sudo: required
addons:
  chrome: stable
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - wget -N https://chromedriver.storage.googleapis.com/95.0.4638.54/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
  - cd test 
  - pytest 
