# name: Running Code Coverage 
# on: push: 
#       branches:
#         -main
#     pull_request:
#       branches:
#         -main
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     env:
#       OS: ubuntu-latest
#       PYTHON: '3.9'
#     steps:
#     - uses: checkout@v2
#       with:
#         fetch-depth: ‘2’

#     - name: Setup Python
#       uses: actions/setup-python@master
#       with:
#         python-version: 3.7
#     - name: Generate Report
#       run: |
#         pip install pytest-cov
#         pip install -r requirements.txt
#         cd test
#         pip install coverage
#         coverage run -m unittest
#     - name: Upload Coverage to Codecov
#       uses: codecov/codecov-action@v1
#       with: 
#         token: ${{ secrets.CODE_COV_SEC }}

name: Running Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.9.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.7
    - name: Install dependencies
      run: |
        pip install pytest-cov
        pip install -r requirements.txt
        echo requirements installed
    - name: Run the tests
      run: |
          cd test
          pytest --cov=./
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODE_COV_SEC }}
